### ISSUE TITLE
Allow admin to delete images regardless of machines associated with it

### ISSUE THREAD

**Issue by rengolin** [mr-provisioner/mr-provisioner#118]
When trying to delete an image that has machines associated with it, I get a foreign key error on the table "machine". As an admin, I'd like to be able to bypass that restriction and delete the image, with all the machines associated with it losing the image from their configuration.

It may be interesting to add a check-box saying "I want to dissociate machines using this image" for that to happen, or get the error.

It would be cool if a drop-down menu would allow us to assign a new image (of the same type) for the machines that have this image attached (like an upgrade).

**Comment by gemagomez** [comment]
This behaviour was changed at user's request:
https://github.com/mr-provisioner/mr-provisioner/issues/25

Users don't appreciate having images removed from their machines, because it has the potential to mess up the testing they are doing.

**Comment by rengolin** [comment]
I'm not asking to delete regardless, I'm just asking to make it possible, as an admin, to do that, even if that requires an extra checkbox.

**Comment by gemagomez** [comment]
The problem originally was that admins were deleting images that people were using. There are several options to make image management possible and I think it requires a more coordinated approach than allowing admins to delete images for it to suit all users. I opened issue https://github.com/mr-provisioner/mr-provisioner/issues/94 for this reason. Can we please continue this conversation there? This is just a proposed implementation for the same problem.

**Comment by rengolin** [comment]
I think you're trying to fix the wrong problem here. Admins are admins, they should be able to do whatever they please. If they're ignoring their users by deleting what they shouldn't, then well, fix the admin.

If the UI warns the admin that there are machines using it and the admin still wants to delete them, well, making it harder (ie. dissociating all machines by hand) will not stop the admin from deleting the image.

This ticket is *just* about automation: instead of requiring admins to dissociate images from machines before deletion, do that for them while making sure this is **explicitly** what the admin wants, via an additional checkbox.

**Comment by gemagomez** [comment]
This app is for testing. Testing principles apply here. Cleaning up old images is an issue, agreed, but deleting them without the user of the machine knowing leads to unrepeatable test results. We need to do image clean up in a way that users are aware of it and can request to stay on an image for whatever reason. You are oversimplifying the problem by trying to delete images indiscriminately. Moving this conversation to issue #94.
