### ISSUE TITLE
Failures in test_image_list API tests

### ISSUE THREAD

**Issue by BaptisteGerondeau** [mr-provisioner/mr-provisioner#134]
Tests have not been running automatically for a while. This needs figuring out. 

On top of it we have reports of some tests failing, this also needs fixing:

test_image_empty_list (contains "Default bootloader" instead of nothing)
test_image_list (assert 3 == 2, one image too many _it seems_)
test_image_list_with_default_bootloader (assert 4 == 3)
test_delete_image (assert 1 == 0 )

Aside from those : "4 failed, 42 passed in 1.52 seconds"
Full output [here](https://pastebin.com/BartV23G)

I deleted and recreated the api_test Postgres database, running 'python3 run.py db upgrade' each time.
(Note that without python3 I ran into this error : )
```
Traceback (most recent call last):
  File "./run.py", line 3, in <module>
    from mr_provisioner import main
  File "/opt/mr-provisioner/build/mr-provisioner-0.3.2/git/mr_provisioner/__init__.py", line 9, in <module>
    from mr_provisioner.config import apply_config
  File "/opt/mr-provisioner/build/mr-provisioner-0.3.2/git/mr_provisioner/config.py", line 8, in <module>
    from mr_provisioner.ipmi import set_ipmitool
  File "/opt/mr-provisioner/build/mr-provisioner-0.3.2/git/mr_provisioner/ipmi.py", line 26
    def build_command(cmd, *, host=None, username=None, password=None, privilege_level=None,
                            ^
SyntaxError: invalid syntax
```

**Comment by gemagomez** [comment]
Thanks for opening this issue. I need to fix the problem with travis not running our tests on every PR/commit.

**Comment by gemagomez** [comment]
The tests were running, we were not seeing the report due to a migration in the underlying test infrastructure. This problem has been solved.
